# Generated by Django 4.2.7 on 2023-12-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='quantaty',
            new_name='quantity',
        ),
    ]
